### ISSUE TITLE
complete example of use

### ISSUE THREAD

**Issue by rootscript** [splodingsocks/elm-native-module#1]
If you have some time: Can you provide some more detail with an example of use, with other code needed in other files, like `"native-modules": true` in elm-package.json, and what might be needed in Main.elm . I think this module could be be quite useful, with a little extra info.  thanks
I'm guessing that this currently works in Elm 0.17.1?

**Comment by mrmurphy** [comment]
Hi, @rootscript!

I'm sorry it took me so long to get back to you. I made this library pre 0.17 when native modules were totally different.

I'd recommend following this tutorial: https://elmseeds.thaterikperson.com/native-modules in order to learn how native modules work now.

Thanks for the issue! I'll modify the readme.
